name: zoficash
description: Zofi Cash UI Assignment
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_charts: ^22.2.12
  flutter_native_splash: ^2.3.2
  country_code_picker: ^3.0.0
  cupertino_icons: ^1.0.6
  json_annotation: ^4.8.1
  webview_flutter: ^4.2.4
  google_nav_bar: ^5.0.6
  path_provider: ^2.1.1
  hydrated_bloc: ^9.1.2
  flutter_bloc: ^8.1.3
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  go_router: ^10.1.2
  dart_ipify: ^1.1.1
  equatable: ^2.0.5
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.7.1
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6

flutter_launcher_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true

flutter_native_splash:
  image: "assets/images/logo.png"
  color: "#FFFFFF"
  android_12:
    image: "assets/images/logo.png"
  fullscreen: false

flutter:
  uses-material-design: true

  assets:
    - google_fonts/
    - assets/images/
