name: "Build & Release"

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0

      - name: Setup Java JDK
        uses: actions/setup-java@v3.12.0
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Flutter action
        uses: subosito/flutter-action@v2.10.0
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter build apk

      - name: Create Release
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          tag: v1.0.0
          token: ${{ secrets.GITHUB_TOKEN }}
