name: "Build & Release"

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.4
        with:
          java-version: "12.x"

      - name: Flutter action
        uses: subosito/flutter-action@v2.10.0
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter build apk

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "mobile-app/build/app/outputs/flutter-apk/app-release.apk"
          tag: v1.0.${{ github.event.after }}
          token: ${{ secrets.GITHUB_TOKEN }}
